Practice programs based on numpy

In [1]:
import numpy as np

In [16]:
#1.Create a 3x3 matrix with values from 1 to 9.
mat=np.arange(1,10).reshape(3,3)
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
#2.Replace all odd numbers in an array with -1.
arr=np.arange(10)
arr1=np.where(arr%2==0,arr,-1)
arr1

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [25]:
#3.Create an array of shape (4, 4) filled with a single repeating number.
arr=np.ones([4,4])*5
arr

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [36]:
#4.Create a diagonal matrix using a list.
l=[1,2,3,4,5]
mat1=np.diag(l)
mat1

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [38]:
#5.Generate an identity matrix using NumPy.
id=np.eye(5)
id

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [44]:
#6.Create a boolean mask for values > 50 in a random array of 20 ints (1–100).
arr=np.random.randint(1,100,20)
print(arr)
arr=arr>50
print(arr)

[87 47 92 58 75 75 80 15  3 60 46 45 86 73 71 60 72 29 47 27]
[ True False  True  True  True  True  True False False  True False False
  True  True  True  True  True False False False]


In [50]:
#7.Reshape a 1D array of 16 values into a 4x4 matrix.
arr=np.arange(16)
arr.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [60]:
#8.Perform element-wise multiplication between two 1D arrays.
arr1=np.arange(5)
arr2=np.arange(5,10)
mul=arr1*arr2
print(arr1,arr2,'\n',mul)

[0 1 2 3 4] [5 6 7 8 9] 
 [ 0  6 14 24 36]


In [72]:
#9.Swap two rows in a 2D array.
arr=np.array([[1,2,3],[4,5,6]])
a=arr[[0,1]]=arr[[1,0]]
a

array([[4, 5, 6],
       [1, 2, 3]])

In [96]:
#10.Replace NaN values in an array with the column mean.
arr=np.array([[1,2,3,np.nan],[5,6,np.nan,8],[9,np.nan,11,12]])
print(arr)
col_mean=np.nanmean(arr,axis=0)
print(f"col_mean{col_mean}")
nan_index=np.where(np.isnan(arr))
arr[nan_index]=np.take(col_mean,nan_index[1])
arr

[[ 1.  2.  3. nan]
 [ 5.  6. nan  8.]
 [ 9. nan 11. 12.]]
col_mean[ 5.  4.  7. 10.]


array([[ 1.,  2.,  3., 10.],
       [ 5.,  6.,  7.,  8.],
       [ 9.,  4., 11., 12.]])

In [103]:
#11.Compute the dot product of two matrices
mat1=np.array([[1,2],[3,4]])
mat2=np.array([[5,6],[7,8]])
print(f'mat1:\n{mat1}\nmat2:\n{mat2}')
dot_product=np.dot(mat1,mat2)
print("dot product:\n",dot_product)

mat1:
[[1 2]
 [3 4]]
mat2:
[[5 6]
 [7 8]]
dot product:
 [[19 22]
 [43 50]]


In [112]:
#12.Find unique elements and their counts in an array
arr = np.array([1, 2, 2, 3, 4, 4, 4])
unique=np.unique(arr)
count=np.unique(arr,return_counts=True)
print("unique values:",unique)
print("count:",count)

unique values: [1 2 3 4]
count: (array([1, 2, 3, 4]), array([1, 2, 1, 3]))


In [118]:
#13.Stack two arrays vertically and horizontally
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
print("vertically stack:\n",np.vstack((arr1,arr2)))
print("horizontally stack:\n",np.hstack((arr1,arr2)))

vertically stack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
horizontally stack:
 [[1 2 5 6]
 [3 4 7 8]]


In [123]:
#14.Find standard deviation of each row in a 2D array
arr=np.arange(9).reshape(3,3)
std=np.std(arr,axis=1)
std

array([0.81649658, 0.81649658, 0.81649658])

In [134]:
#15.Normalize a NumPy array (0 to 1 scale).
arr=np.array([10,20,30,40,50])
print("original:",arr)
normalised=(arr-arr.min())/(arr.max()-arr.min())
print("after normalised:",normalised)

original: [10 20 30 40 50]
after normalised: [0.   0.25 0.5  0.75 1.  ]
