# programs based on numpy basics

In [1]:
import numpy as np

In [16]:
#1.create a 1D array using linspace and reshape it into a 3X5 matrix,replace all values <5 with 0
arr=np.linspace(1,15,15).reshape(3,5)
print(arr)
replace=np.where(arr<5,0,arr)
print("\n",replace)

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]]

 [[ 0.  0.  0.  0.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]]


In [23]:
#2.create a 5X5 identity matrix and multiply it with an array[1,2,3,4,5]
arr=np.array([1,2,3,4,5])
mat=np.eye(5)
print("identity matrix:\n",mat)
print("After multiplying by array:\n",mat*arr)

identity matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
After multiplying by array:
 [[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]


In [34]:
#3.product prices: filter all prices between 500 and 1000
prices=np.random.randint(100,2000,20)
print("all prices:\n",prices)
f=prices[(prices>=500) & (prices<=1000)]
print("after applying filter for prices betn 500 to 1000:\n",f)


all prices:
 [1629  773 1264  937 1913 1944  343  920 1283 1747 1956  633  854  522
  159  206 1171  925 1430  585]
after applying filter for prices betn 500 to 1000:
 [773 937 920 633 854 522 925 585]


In [37]:
#4.count how many votes >8 in each row
votes=np.random.randint(1,11,(5,4))  #5 people 4 questions
print("votes:\n",votes)
count=np.sum(votes>8,axis=1)
print("count:\n",count)

votes:
 [[ 1  4  6  1]
 [ 5  5 10  5]
 [ 4  4  1  7]
 [ 7  4  6  4]
 [ 2  9  5  5]]
count:
 [0 1 0 0 1]


In [50]:
#5.find product with highest total rating
rate=np.random.randint(1,11,(8,5)) #8 users 5 products
print("ratings :\n",rate)
print("Total:",rate.sum(axis=0))
high=np.argmax(rate.sum(axis=0))
print("index of highest rated product:",high)


ratings :
 [[ 8  3  6  5  8]
 [ 4  8  1  1  6]
 [ 3  6  8  6 10]
 [ 7 10  6  2  1]
 [ 6  5 10  8 10]
 [ 5  3 10  7  6]
 [ 8  6 10  9  6]
 [ 8  4  6  8  4]]
Total: [49 45 57 46 51]
index of highest rated product: 2


In [58]:
#6.apply 10% discount where price > 1000
prices=np.random.randint(500,2000,10)
discounted=np.where(prices>1000,prices*0.9,prices)
print("oringinal prices:\n",prices)
print("discounted prices:\n",discounted)

oringinal prices:
 [ 815 1406 1793  951 1202  992 1779 1857 1724 1429]
discounted prices:
 [ 815.  1265.4 1613.7  951.  1081.8  992.  1601.1 1671.3 1551.6 1286.1]


In [70]:
#7.count students who are present all 5 days 
attendence=np.random.randint(0,2,(10,5))  #0-absent 1-present 
whole=np.all(attendence==1,axis=1)
print("Students attendence:\n",attendence)
print("present all 5 days:\n",np.where(whole==True))

Students attendence:
 [[1 0 1 0 0]
 [1 1 0 1 0]
 [1 0 0 1 1]
 [0 0 1 0 0]
 [0 1 0 0 0]
 [0 1 0 0 1]
 [1 1 1 1 0]
 [0 1 0 0 0]
 [1 1 1 1 1]
 [1 0 0 1 1]]
present all 5 days:
 (array([8]),)


In [84]:
#8.find the outliers(>mean+2*std) and replace with 0
data=np.random.normal(50,10,(6,6))
print("Data:\n",data)
mean=np.mean(data)
std=np.std(data)
filtered=np.where(data>mean+2*std,0,data)
print("outliers are denoted by zero:\n",filtered)

Data:
 [[52.04049764 54.32424291 45.51683092 48.77610416 57.24687449 51.63718552]
 [59.41467602 63.13314981 61.88894232 43.37289093 44.35995746 56.88763661]
 [42.90010386 41.46486635 42.78512202 49.63131813 64.11644496 41.6519661 ]
 [56.13238253 47.20612413 59.81970781 57.44445708 57.15613331 42.98685771]
 [56.18251545 52.79388734 51.71622576 50.10870854 59.69333496 60.58502564]
 [48.66352898 35.25680535 73.12371689 36.78204996 40.98774618 87.34596483]]
outliers are denoted by zero:
 [[52.04049764 54.32424291 45.51683092 48.77610416 57.24687449 51.63718552]
 [59.41467602 63.13314981 61.88894232 43.37289093 44.35995746 56.88763661]
 [42.90010386 41.46486635 42.78512202 49.63131813 64.11644496 41.6519661 ]
 [56.13238253 47.20612413 59.81970781 57.44445708 57.15613331 42.98685771]
 [56.18251545 52.79388734 51.71622576 50.10870854 59.69333496 60.58502564]
 [48.66352898 35.25680535 73.12371689 36.78204996 40.98774618  0.        ]]


In [89]:
#9.print pass or fail for 10 students based on 5 subjects marks
marks=np.random.randint(20,100,(10,5))
result=np.where(np.any(marks<30,axis=1),'Fail','Pass')
print("marks:\n",marks)
print("Result:\n",result)

marks:
 [[57 88 63 79 36]
 [52 44 89 84 84]
 [41 67 75 58 21]
 [73 23 68 35 62]
 [52 55 82 31 37]
 [58 57 96 87 88]
 [53 93 82 29 45]
 [85 80 72 84 64]
 [95 41 21 54 34]
 [70 95 76 96 44]]
Result:
 ['Pass' 'Pass' 'Fail' 'Fail' 'Pass' 'Pass' 'Fail' 'Pass' 'Fail' 'Pass']


In [102]:
#10.mark all expenses >25000 as 'Over budget'
exp=np.random.randint(1000,50000,(5,6)).astype(object)
exp[exp.astype(int)>25000]="OverBudget"
print("expenses matrix\n",exp)


expenses matrix
 [['OverBudget' 2982 3088 16928 'OverBudget' 'OverBudget']
 ['OverBudget' 19235 5868 11140 'OverBudget' 1916]
 [19615 9241 14737 12889 'OverBudget' 'OverBudget']
 [14684 24015 'OverBudget' 10193 19994 17638]
 [10893 'OverBudget' 'OverBudget' 'OverBudget' 20983 4405]]
