**Programs based on numpy basics concepts like array and its functions**

In [2]:
import numpy as np

In [3]:
#1.create an array and find even numbers
num=np.array([1,2,3,4,5,6,7,8,9,10])
even=num[num %2 ==0]
print("Even numbers:",even)

Even numbers: [ 2  4  6  8 10]


In [4]:
#2.create a 3X3 identity matrix
matrix=np.eye(3)
print("identity matrix of 3X3:\n",matrix)

identity matrix of 3X3:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
#3.reshape a 1D array to 3X4
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr1=arr.reshape([3,4])
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [6]:
#4.create matrix of 5s using ones()
mat=np.ones([4,3])*5
mat

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [7]:
#5.print dimensions,size and shape of a matrix
mat1=np.arange(1,13).reshape([3,4])
print("matrix of 3X4:\n",mat1)
print("dimensions of matrix:",mat1.ndim)
print("size of matrix:",mat1.size)
print("shape of matrix:",mat1.shape)
print("data type of matrix:",mat1.dtype)

matrix of 3X4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
dimensions of matrix: 2
size of matrix: 12
shape of matrix: (3, 4)
data type of matrix: int64


In [8]:
#6.create a linspace array of 10 points between 0 and 1
lins=np.linspace(0,1,10,retstep=True)
print(lins)

(array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ]), np.float64(0.1111111111111111))


In [9]:
#7.create a 4X4 zeros array and change diagonal to 7
zero=np.zeros((4,4))
np.fill_diagonal(zero,7)
zero

array([[7., 0., 0., 0.],
       [0., 7., 0., 0.],
       [0., 0., 7., 0.],
       [0., 0., 0., 7.]])

In [10]:
#8.slice center 2X2 part from 4X4 matrix
m=np.arange(16).reshape(4,4)
center=m[1:3,1:3]
print("Matrix:\n",m)
print("Center :\n",center)

Matrix:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Center :
 [[ 5  6]
 [ 9 10]]


In [11]:
#9.create a 3D array 
ar=np.arange(27).reshape(3,3,3)
ar

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [13]:
#10.create an array and reverse it
a=np.arange(10)
reverse=a[::-1]
print("original:",a)
print("reversed:",reverse)

original: [0 1 2 3 4 5 6 7 8 9]
reversed: [9 8 7 6 5 4 3 2 1 0]
