# Progrmas based on numpy !

In [3]:
import numpy as np

In [9]:
#1.create 5X5 matrix where each row is [1,2,3,4,5] using broadcasting
row=[1,2,3,4,5]
mat=np.ones((5,1))*row
mat

array([[1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.]])

In [19]:
#2.replace all negative numbers with their positive in random array 
arr=np.random.randint(-100,100,10)
print("oringinal array:",arr)
positive=np.where(arr<0,-arr,arr)
print("positive:",positive)

oringinal array: [  0 -92  33 -81  93 -22  56  19  50 -22]
positive: [ 0 92 33 81 93 22 56 19 50 22]


In [27]:
#3.find top 3 largest elements and their indices
arr=np.random.randint(0,100,10)
print("array:",arr)
ind=np.argsort(arr)[-3:][::-1]
print("top 3 largest value's index:",ind)
val=arr[ind]
print("top 3 largest value",val)

array: [64 90 19 64  9 27 57  8 86 53]
top 3 largest value's index: [1 8 0]
top 3 largest value [90 86 64]


In [37]:
#4.print 4X4 matrix and find maximum of digonal element and its index
mat=np.random.randint(1,50,(4,4))
print("matrix:\n",mat)
diagonal=np.diag(mat)
print(f"maximum of digonal element is:{np.max(diagonal)} and its index is:{np.argmax(diagonal)}")

matrix:
 [[29 36 39 25]
 [30 11 13 16]
 [ 8  7 29 24]
 [ 3 42 33  2]]
maximum of digonal element is:29 and its index is:0


In [39]:
#5.set all elements below column mean to zero
mat=np.random.randint(1,100,(4,5))
col_means=mat.mean(axis=0)
result=np.where(mat<col_means,0,mat)
print("original:\n",mat)
print("column means:",col_means)
print("below column mean to zero\n",result)

original:
 [[26  9 14 17  6]
 [95 29 94  4 81]
 [83 54  3  8 26]
 [54 92 45 93 82]]
column means: [64.5  46.   39.   30.5  48.75]
below column mean to zero
 [[ 0  0  0  0  0]
 [95  0 94  0 81]
 [83 54  0  0  0]
 [ 0 92 45 93 82]]


In [40]:
#6.Extract  every 3rd element in reverse
arr=np.random.randint(1,100,20)
print("array:\n",arr)
print("every 3rd element in reverse:\n",arr[::-3])

array:
 [61 35 75 91 65 46 33 53 38 14 99 54 45 56 92 59 25 61 54 19]
every 3rd element in reverse:
 [19 25 56 99 53 65 35]


In [43]:
#7.find distance of each element from the mean
arr=np.random.randint(1,100,10)
m=np.mean(arr)
d=arr-m
print("array:\n",arr)
print("mean:\n",m)
print("distance from mean:\n",d)

array:
 [65 17 61 68 88 75 38 22 38 95]
mean:
 56.7
distance from mean:
 [  8.3 -39.7   4.3  11.3  31.3  18.3 -18.7 -34.7 -18.7  38.3]


In [46]:

#ARRAY 
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
arr


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [47]:
#8.Extract center elments
arr[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

In [48]:
#9.extract 11,12
arr[2,2:]

array([11, 12])

In [50]:
#10.extract 3
print(arr[0,2])

3
